# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from grpc_wrapper.pb2 import Transfer_pb2 as Transfer__pb2


class TransferStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.sendDicToDic = channel.unary_unary(
        '/Transfer/sendDicToDic',
        request_serializer=Transfer__pb2.Request.SerializeToString,
        response_deserializer=Transfer__pb2.Response.FromString,
        )
    self.sendArrToDic = channel.unary_unary(
        '/Transfer/sendArrToDic',
        request_serializer=Transfer__pb2.ArrayRequest.SerializeToString,
        response_deserializer=Transfer__pb2.Response.FromString,
        )
    self.sendDicToArr = channel.unary_unary(
        '/Transfer/sendDicToArr',
        request_serializer=Transfer__pb2.Request.SerializeToString,
        response_deserializer=Transfer__pb2.ArrayResponse.FromString,
        )
    self.sendArrToArr = channel.unary_unary(
        '/Transfer/sendArrToArr',
        request_serializer=Transfer__pb2.ArrayRequest.SerializeToString,
        response_deserializer=Transfer__pb2.ArrayResponse.FromString,
        )
    self.send = channel.unary_unary(
        '/Transfer/send',
        request_serializer=Transfer__pb2.ArrayRequest.SerializeToString,
        response_deserializer=Transfer__pb2.ArrayResponse.FromString,
        )


class TransferServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def sendDicToDic(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def sendArrToDic(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def sendDicToArr(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def sendArrToArr(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def send(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TransferServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'sendDicToDic': grpc.unary_unary_rpc_method_handler(
          servicer.sendDicToDic,
          request_deserializer=Transfer__pb2.Request.FromString,
          response_serializer=Transfer__pb2.Response.SerializeToString,
      ),
      'sendArrToDic': grpc.unary_unary_rpc_method_handler(
          servicer.sendArrToDic,
          request_deserializer=Transfer__pb2.ArrayRequest.FromString,
          response_serializer=Transfer__pb2.Response.SerializeToString,
      ),
      'sendDicToArr': grpc.unary_unary_rpc_method_handler(
          servicer.sendDicToArr,
          request_deserializer=Transfer__pb2.Request.FromString,
          response_serializer=Transfer__pb2.ArrayResponse.SerializeToString,
      ),
      'sendArrToArr': grpc.unary_unary_rpc_method_handler(
          servicer.sendArrToArr,
          request_deserializer=Transfer__pb2.ArrayRequest.FromString,
          response_serializer=Transfer__pb2.ArrayResponse.SerializeToString,
      ),
      'send': grpc.unary_unary_rpc_method_handler(
          servicer.send,
          request_deserializer=Transfer__pb2.ArrayRequest.FromString,
          response_serializer=Transfer__pb2.ArrayResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Transfer', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
