# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Transfer.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

from grpc_wrapper.pb2 import Tensor_pb2 as Tensor__pb2

DESCRIPTOR = _descriptor.FileDescriptor(
  name='Transfer.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0eTransfer.proto\x1a\x0cTensor.proto\"w\n\x0ePredictRequest\x12)\n\x05input\x18\x01 \x03(\x0b\x32\x1a.PredictRequest.InputEntry\x1a:\n\nInputEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1b\n\x05value\x18\x02 \x01(\x0b\x32\x0c.TensorProto:\x02\x38\x01\"|\n\x0fPredictResponse\x12,\n\x06output\x18\x01 \x03(\x0b\x32\x1c.PredictResponse.OutputEntry\x1a;\n\x0bOutputEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1b\n\x05value\x18\x02 \x01(\x0b\x32\x0c.TensorProto:\x02\x38\x01\x32:\n\x08Transfer\x12.\n\x07predict\x12\x0f.PredictRequest\x1a\x10.PredictResponse\"\x00\x62\x06proto3')
  ,
  dependencies=[Tensor__pb2.DESCRIPTOR,])




_PREDICTREQUEST_INPUTENTRY = _descriptor.Descriptor(
  name='InputEntry',
  full_name='PredictRequest.InputEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='PredictRequest.InputEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='PredictRequest.InputEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=93,
  serialized_end=151,
)

_PREDICTREQUEST = _descriptor.Descriptor(
  name='PredictRequest',
  full_name='PredictRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='input', full_name='PredictRequest.input', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_PREDICTREQUEST_INPUTENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=151,
)


_PREDICTRESPONSE_OUTPUTENTRY = _descriptor.Descriptor(
  name='OutputEntry',
  full_name='PredictResponse.OutputEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='PredictResponse.OutputEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='PredictResponse.OutputEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=218,
  serialized_end=277,
)

_PREDICTRESPONSE = _descriptor.Descriptor(
  name='PredictResponse',
  full_name='PredictResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='output', full_name='PredictResponse.output', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_PREDICTRESPONSE_OUTPUTENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=153,
  serialized_end=277,
)

_PREDICTREQUEST_INPUTENTRY.fields_by_name['value'].message_type = Tensor__pb2._TENSORPROTO
_PREDICTREQUEST_INPUTENTRY.containing_type = _PREDICTREQUEST
_PREDICTREQUEST.fields_by_name['input'].message_type = _PREDICTREQUEST_INPUTENTRY
_PREDICTRESPONSE_OUTPUTENTRY.fields_by_name['value'].message_type = Tensor__pb2._TENSORPROTO
_PREDICTRESPONSE_OUTPUTENTRY.containing_type = _PREDICTRESPONSE
_PREDICTRESPONSE.fields_by_name['output'].message_type = _PREDICTRESPONSE_OUTPUTENTRY
DESCRIPTOR.message_types_by_name['PredictRequest'] = _PREDICTREQUEST
DESCRIPTOR.message_types_by_name['PredictResponse'] = _PREDICTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PredictRequest = _reflection.GeneratedProtocolMessageType('PredictRequest', (_message.Message,), dict(

  InputEntry = _reflection.GeneratedProtocolMessageType('InputEntry', (_message.Message,), dict(
    DESCRIPTOR = _PREDICTREQUEST_INPUTENTRY,
    __module__ = 'Transfer_pb2'
    # @@protoc_insertion_point(class_scope:PredictRequest.InputEntry)
    ))
  ,
  DESCRIPTOR = _PREDICTREQUEST,
  __module__ = 'Transfer_pb2'
  # @@protoc_insertion_point(class_scope:PredictRequest)
  ))
_sym_db.RegisterMessage(PredictRequest)
_sym_db.RegisterMessage(PredictRequest.InputEntry)

PredictResponse = _reflection.GeneratedProtocolMessageType('PredictResponse', (_message.Message,), dict(

  OutputEntry = _reflection.GeneratedProtocolMessageType('OutputEntry', (_message.Message,), dict(
    DESCRIPTOR = _PREDICTRESPONSE_OUTPUTENTRY,
    __module__ = 'Transfer_pb2'
    # @@protoc_insertion_point(class_scope:PredictResponse.OutputEntry)
    ))
  ,
  DESCRIPTOR = _PREDICTRESPONSE,
  __module__ = 'Transfer_pb2'
  # @@protoc_insertion_point(class_scope:PredictResponse)
  ))
_sym_db.RegisterMessage(PredictResponse)
_sym_db.RegisterMessage(PredictResponse.OutputEntry)


_PREDICTREQUEST_INPUTENTRY.has_options = True
_PREDICTREQUEST_INPUTENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
_PREDICTRESPONSE_OUTPUTENTRY.has_options = True
_PREDICTRESPONSE_OUTPUTENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))

_TRANSFER = _descriptor.ServiceDescriptor(
  name='Transfer',
  full_name='Transfer',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=279,
  serialized_end=337,
  methods=[
  _descriptor.MethodDescriptor(
    name='predict',
    full_name='Transfer.predict',
    index=0,
    containing_service=None,
    input_type=_PREDICTREQUEST,
    output_type=_PREDICTRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TRANSFER)

DESCRIPTOR.services_by_name['Transfer'] = _TRANSFER

# @@protoc_insertion_point(module_scope)
