# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from grpc_wrapper.pb2 import Transfer_pb2 as Transfer__pb2


class TransferStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.predict = channel.unary_unary(
        '/Transfer/predict',
        request_serializer=Transfer__pb2.PredictRequest.SerializeToString,
        response_deserializer=Transfer__pb2.PredictResponse.FromString,
        )


class TransferServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def predict(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TransferServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'predict': grpc.unary_unary_rpc_method_handler(
          servicer.predict,
          request_deserializer=Transfer__pb2.PredictRequest.FromString,
          response_serializer=Transfer__pb2.PredictResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Transfer', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
